// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjtcwmukpquediyvovyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqdGN3bXVrcHF1ZWRpeXZvdnl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NzcyMzIsImV4cCI6MjA1NjE1MzIzMn0.NSsvE_8EQ5N8qyAPZ3_1dmPiH4wyLvqW8-PgQYoCEC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);